# H2 database properties
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: Tiku@123
    url: jdbc:h2:mem:test
    username: root
#    hikari:
#      maximum-pool-size: 20
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
server:
  port: 8082
